# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainWindowUI.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setEnabled(True)
        MainWindow.resize(831, 677)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(831, 677))
        MainWindow.setMaximumSize(QtCore.QSize(831, 677))
        MainWindow.setMouseTracking(True)
        MainWindow.setStyleSheet("")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setMouseTracking(True)
        self.centralwidget.setObjectName("centralwidget")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(620, 310, 201, 301))
        self.groupBox.setMinimumSize(QtCore.QSize(0, 0))
        self.groupBox.setMaximumSize(QtCore.QSize(80000, 60000))
        self.groupBox.setStyleSheet("")
        self.groupBox.setObjectName("groupBox")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.groupBox)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(20, 20, 161, 201))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.fpsLabel = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.fpsLabel.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.fpsLabel.setAutoFillBackground(True)
        self.fpsLabel.setObjectName("fpsLabel")
        self.verticalLayout.addWidget(self.fpsLabel, 0, QtCore.Qt.AlignHCenter)
        self.fpsSlider = QtWidgets.QSlider(self.verticalLayoutWidget)
        self.fpsSlider.setMinimum(1)
        self.fpsSlider.setMaximum(13)
        self.fpsSlider.setPageStep(1)
        self.fpsSlider.setProperty("value", 3)
        self.fpsSlider.setOrientation(QtCore.Qt.Horizontal)
        self.fpsSlider.setObjectName("fpsSlider")
        self.verticalLayout.addWidget(self.fpsSlider)
        self.durationLabel = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.durationLabel.setObjectName("durationLabel")
        self.verticalLayout.addWidget(self.durationLabel, 0, QtCore.Qt.AlignHCenter)
        self.duraSlider = QtWidgets.QSlider(self.verticalLayoutWidget)
        self.duraSlider.setMinimum(1)
        self.duraSlider.setMaximum(31)
        self.duraSlider.setPageStep(1)
        self.duraSlider.setProperty("value", 5)
        self.duraSlider.setOrientation(QtCore.Qt.Horizontal)
        self.duraSlider.setObjectName("duraSlider")
        self.verticalLayout.addWidget(self.duraSlider)
        self.interLabel = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.interLabel.setEnabled(False)
        self.interLabel.setObjectName("interLabel")
        self.verticalLayout.addWidget(self.interLabel, 0, QtCore.Qt.AlignHCenter)
        self.interSlider = QtWidgets.QSlider(self.verticalLayoutWidget)
        self.interSlider.setEnabled(False)
        self.interSlider.setMinimum(-1)
        self.interSlider.setMaximum(11)
        self.interSlider.setPageStep(1)
        self.interSlider.setProperty("value", 5)
        self.interSlider.setOrientation(QtCore.Qt.Horizontal)
        self.interSlider.setObjectName("interSlider")
        self.verticalLayout.addWidget(self.interSlider)
        self.resoLabel = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.resoLabel.setObjectName("resoLabel")
        self.verticalLayout.addWidget(self.resoLabel, 0, QtCore.Qt.AlignHCenter)
        self.resolSlider = QtWidgets.QSlider(self.verticalLayoutWidget)
        self.resolSlider.setMinimum(-3)
        self.resolSlider.setMaximum(5)
        self.resolSlider.setPageStep(1)
        self.resolSlider.setProperty("value", -1)
        self.resolSlider.setOrientation(QtCore.Qt.Horizontal)
        self.resolSlider.setObjectName("resolSlider")
        self.verticalLayout.addWidget(self.resolSlider)
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.groupBox)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(10, 230, 181, 61))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.raidusButton = QtWidgets.QRadioButton(self.verticalLayoutWidget_2)
        self.raidusButton.setEnabled(True)
        self.raidusButton.setMouseTracking(False)
        self.raidusButton.setAcceptDrops(False)
        self.raidusButton.setAutoFillBackground(False)
        self.raidusButton.setCheckable(True)
        self.raidusButton.setChecked(True)
        self.raidusButton.setAutoExclusive(True)
        self.raidusButton.setObjectName("raidusButton")
        self.verticalLayout_2.addWidget(self.raidusButton)
        self.freButton = QtWidgets.QRadioButton(self.verticalLayoutWidget_2)
        self.freButton.setChecked(False)
        self.freButton.setObjectName("freButton")
        self.verticalLayout_2.addWidget(self.freButton)
        self.gridLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(621, 220, 201, 81))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.backButton = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.backButton.setEnabled(False)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setBold(False)
        font.setWeight(50)
        self.backButton.setFont(font)
        self.backButton.setObjectName("backButton")
        self.gridLayout.addWidget(self.backButton, 1, 0, 1, 1)
        self.solveButton = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.solveButton.setEnabled(False)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.solveButton.setFont(font)
        self.solveButton.setObjectName("solveButton")
        self.gridLayout.addWidget(self.solveButton, 0, 0, 1, 1)
        self.runButton = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.runButton.setEnabled(False)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setBold(False)
        font.setWeight(50)
        self.runButton.setFont(font)
        self.runButton.setObjectName("runButton")
        self.gridLayout.addWidget(self.runButton, 0, 1, 1, 1)
        self.clearButton = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.clearButton.setEnabled(True)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setBold(False)
        font.setWeight(50)
        self.clearButton.setFont(font)
        self.clearButton.setObjectName("clearButton")
        self.gridLayout.addWidget(self.clearButton, 1, 1, 1, 1)
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setGeometry(QtCore.QRect(0, 610, 830, 20))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(9, 9, 601, 601))
        self.frame.setMinimumSize(QtCore.QSize(601, 601))
        self.frame.setMaximumSize(QtCore.QSize(601, 601))
        self.frame.setMouseTracking(True)
        self.frame.setStyleSheet("background-color: rgb(255, 255, 191);\n"
"")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame.setObjectName("frame")
        self.previewLabel = QtWidgets.QLabel(self.centralwidget)
        self.previewLabel.setGeometry(QtCore.QRect(621, 14, 201, 201))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(20)
        self.previewLabel.setFont(font)
        self.previewLabel.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.previewLabel.setObjectName("previewLabel")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 831, 26))
        self.menubar.setObjectName("menubar")
        self.menuWindow = QtWidgets.QMenu(self.menubar)
        self.menuWindow.setEnabled(True)
        self.menuWindow.setObjectName("menuWindow")
        self.menuView = QtWidgets.QMenu(self.menubar)
        self.menuView.setEnabled(True)
        self.menuView.setObjectName("menuView")
        self.menuPrameter = QtWidgets.QMenu(self.menuView)
        self.menuPrameter.setEnabled(False)
        self.menuPrameter.setObjectName("menuPrameter")
        self.menuinterpolation = QtWidgets.QMenu(self.menuView)
        self.menuinterpolation.setEnabled(False)
        self.menuinterpolation.setObjectName("menuinterpolation")
        self.menuExport = QtWidgets.QMenu(self.menubar)
        self.menuExport.setEnabled(True)
        self.menuExport.setObjectName("menuExport")
        self.menuHelp = QtWidgets.QMenu(self.menubar)
        self.menuHelp.setEnabled(True)
        self.menuHelp.setObjectName("menuHelp")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setEnabled(True)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionRun = QtWidgets.QAction(MainWindow)
        self.actionRun.setEnabled(False)
        self.actionRun.setObjectName("actionRun")
        self.actionClear = QtWidgets.QAction(MainWindow)
        self.actionClear.setObjectName("actionClear")
        self.actionExit = QtWidgets.QAction(MainWindow)
        self.actionExit.setObjectName("actionExit")
        self.actionlines = QtWidgets.QAction(MainWindow)
        self.actionlines.setCheckable(True)
        self.actionlines.setChecked(True)
        self.actionlines.setObjectName("actionlines")
        self.actioncircles = QtWidgets.QAction(MainWindow)
        self.actioncircles.setCheckable(True)
        self.actioncircles.setChecked(True)
        self.actioncircles.setObjectName("actioncircles")
        self.actiondots = QtWidgets.QAction(MainWindow)
        self.actiondots.setCheckable(True)
        self.actiondots.setChecked(True)
        self.actiondots.setObjectName("actiondots")
        self.actionopen_Image = QtWidgets.QAction(MainWindow)
        self.actionopen_Image.setObjectName("actionopen_Image")
        self.actionclose_image = QtWidgets.QAction(MainWindow)
        self.actionclose_image.setObjectName("actionclose_image")
        self.actionrefresh = QtWidgets.QAction(MainWindow)
        self.actionrefresh.setObjectName("actionrefresh")
        self.action_text = QtWidgets.QAction(MainWindow)
        self.action_text.setEnabled(False)
        self.action_text.setObjectName("action_text")
        self.action_mp4 = QtWidgets.QAction(MainWindow)
        self.action_mp4.setEnabled(False)
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.action_mp4.setFont(font)
        self.action_mp4.setObjectName("action_mp4")
        self.action_gif = QtWidgets.QAction(MainWindow)
        self.action_gif.setObjectName("action_gif")
        self.actionnone = QtWidgets.QAction(MainWindow)
        self.actionnone.setCheckable(True)
        self.actionnone.setObjectName("actionnone")
        self.actionlinear = QtWidgets.QAction(MainWindow)
        self.actionlinear.setCheckable(True)
        self.actionlinear.setChecked(True)
        self.actionlinear.setObjectName("actionlinear")
        self.actioncubic = QtWidgets.QAction(MainWindow)
        self.actioncubic.setCheckable(True)
        self.actioncubic.setObjectName("actioncubic")
        self.actionGitHub = QtWidgets.QAction(MainWindow)
        self.actionGitHub.setEnabled(True)
        self.actionGitHub.setObjectName("actionGitHub")
        self.actionAbout = QtWidgets.QAction(MainWindow)
        self.actionAbout.setObjectName("actionAbout")
        self.menuWindow.addAction(self.actionRun)
        self.menuWindow.addAction(self.actionClear)
        self.menuWindow.addSeparator()
        self.menuWindow.addAction(self.actionExit)
        self.menuPrameter.addAction(self.actionlines)
        self.menuPrameter.addAction(self.actioncircles)
        self.menuPrameter.addAction(self.actiondots)
        self.menuinterpolation.addAction(self.actionnone)
        self.menuinterpolation.addAction(self.actionlinear)
        self.menuinterpolation.addAction(self.actioncubic)
        self.menuView.addAction(self.menuPrameter.menuAction())
        self.menuView.addAction(self.menuinterpolation.menuAction())
        self.menuView.addSeparator()
        self.menuView.addAction(self.actionopen_Image)
        self.menuView.addAction(self.actionclose_image)
        self.menuView.addSeparator()
        self.menuView.addAction(self.actionrefresh)
        self.menuExport.addAction(self.action_text)
        self.menuExport.addAction(self.action_mp4)
        self.menuExport.addAction(self.action_gif)
        self.menuHelp.addAction(self.actionGitHub)
        self.menuHelp.addSeparator()
        self.menuHelp.addAction(self.actionAbout)
        self.menubar.addAction(self.menuWindow.menuAction())
        self.menubar.addAction(self.menuView.menuAction())
        self.menubar.addAction(self.menuExport.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "EpiCycles"))
        self.groupBox.setTitle(_translate("MainWindow", "Options"))
        self.fpsLabel.setText(_translate("MainWindow", "30 FPS"))
        self.durationLabel.setText(_translate("MainWindow", "10s duration"))
        self.interLabel.setText(_translate("MainWindow", "5 interpolate"))
        self.resoLabel.setText(_translate("MainWindow", "0.25 resolution"))
        self.raidusButton.setText(_translate("MainWindow", "sorted by radius"))
        self.freButton.setText(_translate("MainWindow", "sorted by frequency"))
        self.backButton.setText(_translate("MainWindow", "Back"))
        self.solveButton.setText(_translate("MainWindow", "Solve"))
        self.runButton.setText(_translate("MainWindow", "Run"))
        self.clearButton.setText(_translate("MainWindow", "Clear"))
        self.previewLabel.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\">Preview Pic</p></body></html>"))
        self.menuWindow.setTitle(_translate("MainWindow", "Window"))
        self.menuView.setTitle(_translate("MainWindow", "View"))
        self.menuPrameter.setTitle(_translate("MainWindow", "display"))
        self.menuinterpolation.setTitle(_translate("MainWindow", "interpolation"))
        self.menuExport.setTitle(_translate("MainWindow", "Export"))
        self.menuHelp.setTitle(_translate("MainWindow", "Help"))
        self.actionRun.setText(_translate("MainWindow", "Run"))
        self.actionClear.setText(_translate("MainWindow", "Clear"))
        self.actionExit.setText(_translate("MainWindow", "Exit"))
        self.actionlines.setText(_translate("MainWindow", "lines"))
        self.actioncircles.setText(_translate("MainWindow", "circles"))
        self.actiondots.setText(_translate("MainWindow", "dots"))
        self.actionopen_Image.setText(_translate("MainWindow", "open image"))
        self.actionclose_image.setText(_translate("MainWindow", "close image"))
        self.actionrefresh.setText(_translate("MainWindow", "refresh"))
        self.action_text.setText(_translate("MainWindow", "*.txt"))
        self.action_mp4.setText(_translate("MainWindow", "*.mp4"))
        self.action_gif.setText(_translate("MainWindow", "*.gif"))
        self.actionnone.setText(_translate("MainWindow", "none"))
        self.actionlinear.setText(_translate("MainWindow", "linear"))
        self.actioncubic.setText(_translate("MainWindow", "cubic"))
        self.actionGitHub.setText(_translate("MainWindow", "GitHub"))
        self.actionAbout.setText(_translate("MainWindow", "About..."))
